### ISSUE TITLE
How to run it against online vitepress? 

### ISSUE THREAD

**Issue by Jeff-Tian** [condorheroblog/vitepress-export-pdf#11]
Instead of starting a local dev version, could you make any configurations to generate it from the online build version?

**Comment by condorheroblog** [comment]
An important purpose of running the service locally is to obtain all the routes of the website, so that it can automatically navigate to the corresponding page to generate a PDF.

I don't have any good solution for this problem

**Comment by Jeff-Tian** [comment]
Actually the `html-export-pdf-cli` is what I was asking:
```
html-export-pdf-cli https://online.vite.press/main.html -o result.pdf
````

Thank you!
