### ISSUE TITLE
Internal anchor link references are forced external

### ISSUE THREAD

**Issue by kwesterfeld2** [condorheroblog/vitepress-export-pdf#13]
I'm not sure exactly how to describe what is happening other than, every anchor link in my vitepress site, when rendered to HTML, refers to the origin passed to the export configuration, rather than an internal document link.

Is this configurable, perhaps through a puppeteer option?

**Comment by condorheroblog** [comment]
Hi! Is it the effect of the GIF demonstration below. **You can also see that the internal anchor links in the PDF I generated are clickable**.

![2023-08-26 09-35-16 2023-08-26 09_40_54](https://github.com/condorheroblog/vitepress-export-pdf/assets/47056890/200b4faa-ad74-4dae-b5eb-a13be0de408e)

The HTML code for this effect is as follows:

![image](https://github.com/condorheroblog/vitepress-export-pdf/assets/47056890/4b403f30-7cdc-4dcc-95d7-510fa8a74863)

http://localhost:5173/guide/theme-team-page.html#vpteammembers

I hope it can help you.

**Comment by kwesterfeld2** [comment]
This is very helpful to know that I have a chance to make this work!

What I can see with all of our page anchor links is that the href has a full url—but that the url contains the full origin of the site.  The generated site is still single page but I dont know what I did to the configuration to cause that.  When I use the html site it works without page refresh, but the generated pdf renders links to our external site as if I clicked on a web url.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by condorheroblog** [comment]
The rules for generating anchor points in the MD file of VitePress are as follows:

```md
`<VPTeamMembers>`](#vpteammembers)
```

If the `href` is a full link, then it is a link first and an anchor second.

**Comment by kwesterfeld2** [comment]
I am wondering how one would generate cross page links if one can only do links as suggested?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by condorheroblog** [comment]
To handle this requirement, you need to write your own library for merging PDFs.

**Comment by kwesterfeld2** [comment]
It seems like perhaps this is a good addition to your library.  Would you accept a PR for this feature?

Basically, it looks like anchor elements only support page-relative navigation, not cross-page navigation.  The PR I am thinking of working on supports a means to handle cross-page navigation.  We are using the exact recommended syntax found for internal links here: https://vitepress.dev/guide/markdown#internal-links.  It would seem to be a common vitepress usecase.  Example on one of our pages:  [Sharing System Resources](../workload/wlm_concepts.md)


From: CondorHero ***@***.***>
Date: Saturday, August 26, 2023 at 12:23 AM
To: condorheroblog/vitepress-export-pdf ***@***.***>
Cc: Kurt Westerfeld ***@***.***>, Author ***@***.***>
Subject: Re: [condorheroblog/vitepress-export-pdf] Internal anchor link references are forced external (Issue #13)

To handle this requirement, you need to write your own library for merging PDFs.

**Comment by condorheroblog** [comment]
You can research it. If it works, accept PR🥳

**Comment by JounQin** [comment]
So why this issue is closed as `completed`?
