### ISSUE TITLE
export image error

### ISSUE THREAD

**Issue by rjxxr** [condorheroblog/vitepress-export-pdf#15]
![image](https://github.com/condorheroblog/vitepress-export-pdf/assets/87513376/678e650a-58c9-4a88-95ed-c6084a4eeda3)

**Comment by condorheroblog** [comment]
It seems to have nothing to do with my plugin. [vitepress-export-pdf](https://github.com/condorheroblog/vitepress-export-pdf) will first start a service and then access this URL to generate a PDF,
So you can start the service locally and see if it can load properly in the dev environment
