### ISSUE TITLE
Export multiple PDFs (one per language) ?

### ISSUE THREAD

**Issue by aadrian** [condorheroblog/vitepress-export-pdf#17]
Hi,

Considering the separate directory per locale:  https://vitepress.dev/guide/i18n#separate-directory-for-each-locale

What would be the best approach to generate one PDF for each locale at once (since a single PDF containing all languages makes less sense)?

Thank you.

**Comment by condorheroblog** [comment]
When generating the PDFs, make sure that the configuration file config.ts has only one language to solve the problem.

For example:

```ts
export default defineConfig({
  ...shared,
  locales: {
    root: { label: 'English', ...en },
    // zh: { label: '简体中文', ...zh },
    // pt: { label: 'Português', ...pt }
  }
})
```

**Comment by aadrian** [comment]
@condorheroblog 

Thank you for the quick reply !
