### ISSUE TITLE
export docs show "At least two PDF files" error and no output

### ISSUE THREAD

**Issue by zuoez02** [condorheroblog/vitepress-export-pdf#18]
![image](https://github.com/condorheroblog/vitepress-export-pdf/assets/4801955/f749dcdd-f522-4acf-a72f-019c252277a3)
I can check temp pdf files in folder, but error shown.
![image](https://github.com/condorheroblog/vitepress-export-pdf/assets/4801955/37a846af-8a35-48f9-a095-a1f511c71a52)

**Comment by zuoez02** [comment]
oh, I found the closed issue: https://github.com/condorheroblog/vitepress-export-pdf/issues/4

same in windows 11.

current version: 1.0.0-beta.0
nodejs: v18.19.1

**Comment by condorheroblog** [comment]
[v1.0.0](https://github.com/condorheroblog/vitepress-export-pdf/releases/tag/v1.0.0) has released.
