### ISSUE TITLE
doesn't work with `base` in vitepress

### ISSUE THREAD

**Issue by dominikcz** [condorheroblog/vitepress-export-pdf#2]
Hi, it seems like when you use `base` property in .vitepress.config.js like this:

```
export default {
   base: "/subfolder/",
```

Then after export you get a pdf file with all pages, but empty ones with only one line of text in each of them: 
> The server is configured with a public base URL of /subfolder/ - did you mean to visit /subfolder/test.html instead?

**Comment by condorheroblog** [comment]
A good problem. I have fixed this bug. Please install [1.0.0-alpha.2](https://github.com/condorheroblog/vitepress-export-pdf/releases/tag/v1.0.0-alpha.2)
