### ISSUE TITLE
The directory is messy

### ISSUE THREAD

**Issue by Elmer-kun** [condorheroblog/vitepress-export-pdf#20]
when I grneratePDF the directory is:
![1](https://github.com/condorheroblog/vitepress-export-pdf/assets/37469850/f668a752-b565-4de5-ae46-09e7670e9680)
 but my directory may be:
![2](https://github.com/condorheroblog/vitepress-export-pdf/assets/37469850/9ea8c69e-52d5-4777-91ed-8d75a0eb8f1a)

**Comment by condorheroblog** [comment]
No more information
