### ISSUE TITLE
I got an issue on GitHub Actions.

### ISSUE THREAD

**Issue by enchic** [condorheroblog/vitepress-export-pdf#21]
Hello, this plugin has made VitePress really useful.
However, a problem occurred while uploading my VitePress site to GitHub Page.

I'm still not sure if this issue can be resolved in this package or if I should create an issue in another package.
But first, let me share the issue here.

Issue - [ws affected by a DoS when handling a request with many HTTP headers](https://github.com/enchic/gitzza-plaza/security/dependabot/1):

> vitepress-export-pdf@1.0.0 requires ws@8.16.0 via a transitive dependency on puppeteer-core@21.11.0
> No patched version available for ws

Thank you.

**Comment by condorheroblog** [comment]
Sorry, I don't know how to fix it, thanks for your issue.
