### ISSUE TITLE
Help: Directory export still messed up

### ISSUE THREAD

**Issue by jinzhongjia** [condorheroblog/vitepress-export-pdf#25]
我已经参照了示例文件中的内容，结果导出的目录还是混乱的

```ts
(pageA, pageB) => {
	const aIndex = links.findIndex(route => route === pageA.path)
	const bIndex = links.findIndex(route => route === pageB.path)
	return aIndex - bIndex
}
```
关于这个函数存在疑问，该回调会用于对所有页面进行 sort 吗？能否说明一下这个排序在源码哪个部分

另外，如何不导出某些页面，有一部分页面在网页需要，但导出 pdf 并不需要

注：如需提供额外信息请说明

**Comment by condorheroblog** [comment]
1. 默认情况下，对所有的页面进行排序，你可以利用 sorter 进行排序，routeOrder 里面的数组就是你路由的顺序。
```js
sorter: (pageA, pageB) => {
    const aIndex = routeOrder.findIndex(route => route === pageA.path)
    const bIndex = routeOrder.findIndex(route => route === pageB.path)
    return aIndex - bIndex
  },
```
2. 如果你不需要某些路由，需要使用 routePatterns 参数，例如 ["!/zh/**"],  // exclude zh-CN pages

参考：https://github.com/condorheroblog/vitepress-export-pdf/issues/12

**Comment by jinzhongjia** [comment]
感谢解答，还有一个小问题，导出文件命名能否再详细定义，例如使用commit id

pdf_{commit_id} 这种呢

**Comment by condorheroblog** [comment]
可以使用 outFile  自己实现
