### ISSUE TITLE
How to set the level of pdf bookmarks

### ISSUE THREAD

**Issue by chestnutsj** [condorheroblog/vitepress-export-pdf#28]
The implemented pdf exported bookmarks are consistent with the sidebar.

```
text1:
    text2:
         text3: 
            page_title
            page_title
```

Instead of every page having an H1 title

**Comment by condorheroblog** [comment]
Do you want this [outlineTags](https://github.com/condorheroblog/html-export-pdf-cli?tab=readme-ov-file#outline) option in  [html-export-pdf-cli](https://github.com/condorheroblog/html-export-pdf-cli) package.

However, once this parameter is enabled, it is valid for all pages and cannot be configured for one of those pages, so supporting this parameter is not very useful.
