### ISSUE TITLE
Failed to export on Windows system

### ISSUE THREAD

**Issue by aMagicalpole** [condorheroblog/vitepress-export-pdf#4]
## Exception details
![image](https://github.com/condorheroblog/vitepress-export-pdf/assets/54259291/95997eac-7a6d-4e01-8cbe-89ef875b6c19)

Pdf export failed, export dir is empty.

## Reproduction steps

1.  git clone https://github.com/condorheroblog/vitepress-export-pdf.git
2. pnpm install
3. pnpm docs:debug

## environment

node: 16.20.0

**Comment by aMagicalpole** [comment]
Succeeded on macOs, but failed to export on both win10 and win11

**Comment by condorheroblog** [comment]
I have located the specific reason. I used https://github.com/condorheroblog/merge-pdfs when merging PDFs, which relies on https://github.com/mrmlnc/fast-glob, `fast-glob` There is no conversion of the path of the Windows system: https://github.com/mrmlnc/fast-glob/issues/240

However, the author has fixed this bug, and he intends to release v3.3.0 in June—https://github.com/mrmlnc/fast-glob/issues/396, which is to be released this month, so we can wait.

At present, you can turn off the generated outline of the exported PDF through the `pdfOutlines` parameter of the configuration file, which should be able to bypass this bug

```ts
import { defineUserConfig } from "vitepress-export-pdf";

export default defineUserConfig({
	pdfOutlines: false
});
```

You can even go to node_modules to change the code. It’s an expedient measure. Anyway, the author of fast-glob is about to release a new version.

**Comment by condorheroblog** [comment]
Now, you can install [v1.0.0-beta.0](https://github.com/condorheroblog/vitepress-export-pdf/releases/tag/v1.0.0-beta.0)

**Comment by ssdmtank** [comment]
> Now, you can install [v1.0.0-beta.0](https://github.com/condorheroblog/vitepress-export-pdf/releases/tag/v1.0.0-beta.0)现在，您可以安装 v1.0.0-beta.0

also failed when i install 1.0.0-beta.0 in windows
