### ISSUE TITLE
user configured route patterns don't work

### ISSUE THREAD

**Issue by Jeff-Tian** [condorheroblog/vitepress-export-pdf#8]
For example, configure single page pattern:

```
    routePatterns: ["/idea.html"],

```

Still all pages are printed.

## Root cause:
<img width="996" alt="image" src="https://github.com/condorheroblog/vitepress-export-pdf/assets/3367820/c1c4e9e7-8487-4a03-a428-f6f5ec7b3723">

## See the multimatch test

![image](https://github.com/condorheroblog/vitepress-export-pdf/assets/3367820/63cb3848-ef41-4f13-860a-2831fec32657)

**Comment by condorheroblog** [comment]
A more common export scenario is: the user exports all web pages, but does not want to export some specific web pages. At this time, `routePatterns` is very easy to use, just add an exclamation mark in front of the path.

```ts
import { defineUserConfig } from "vitepress-export-pdf";

export default defineUserConfig({
	routePatterns: ["!/about.html"],
});
```


https://github.com/condorheroblog/vitepress-export-pdf/blob/main/src/serverApp.ts#L41-L43

If the default value here is removed, when the user does not want certain pages, it must be written like this


```ts
import { defineUserConfig } from "vitepress-export-pdf";

export default defineUserConfig({
	routePatterns: ["/**", "!/404.html", "!/about.html"],
});
```

It is very troublesome to add `/**` every time.


So, **If you want to export only certain pages, first cancel the export of all pages, and then export specific pages**, For example export only the about page:

```ts
import { defineUserConfig } from "vitepress-export-pdf";

export default defineUserConfig({
	routePatterns: ["!/**", "/about.html"],
});
```

https://github.com/sindresorhus/multimatch/blob/6d514ce93f41a60cdda6b3c232b31610a27b07f7/test/globule.js#L46

In this plugin, only specific pages are exported, I think it should be a low-frequency operation.
